complete -f -c exercism -a "configure" -d "Writes config values to a JSON file."
complete -f -c exercism -a "download" -d "Downloads and saves a specified submission into the local system"
complete -f -c exercism -a "help" -d "Shows a list of commands or help for one command"
complete -f -c exercism -a "open" -d "Opens a browser to exercism.io for the specified submission."
complete -f -c exercism -a "submit" -d "Submits a new iteration to a problem on exercism.io."
complete -f -c exercism -a "troubleshoot" -d "Outputs useful debug information."
complete -f -c exercism -a "upgrade" -d "Upgrades to the latest available version."
complete -f -c exercism -a "version" -d "Outputs version information."
complete -f -c exercism -a "workspace" -d "Outputs the root directory for Exercism exercises."
complete -f -c exercism -s h -l help -d "show help"
complete -f -c exercism -l timeout -a "(seq 0 100 100000)" -d "override default HTTP timeout"
complete -f -c exercism -s v -l verbose -d "turn on verbose logging"
