# You can find the GoReleaser documentation at http://goreleaser.com
project_name: exercism

builds:
- env:
    - CGO_ENABLED=0
  main: ./exercism/main.go
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - openbsd
  goarch:
    - amd64
    - 386
    - arm
    - ppc64
  goarm:
    - 5
    - 6
  ignore:
    - goos: openbsd
      goarch: arm
    - goos: freebsd
      goarch: arm

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      amd64: x86_64
      386: i386
    format_overrides:
    - goos: windows
      format: zip
    files:
      - shell/**/*
      - LICENSE
      - README.md

signs:
- artifacts: checksum

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: exercism
    name: cli

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

# brews:
# We do not use the brew config, which is for taps, not core forumulas. 

snapcrafts:
  -
    name: exercism
    license: MIT
    # Whether to publish the snap to the snapcraft store.
    # Remember you need to `snapcraft login` first.
    # Defaults to false.
    # publish: true
    summary: Command-line client for https://exercism.io
    # https://snapcraft.io/docs/reference/confinement
    confinement: strict
    # A snap of type base to be used as the execution environment for this snap.
    base: core18
    # https://snapcraft.io/docs/reference/channels
    grade: stable
    description: Exercism is an online platform designed to help you improve your coding skills through practice and mentorship. Exercism provides you with thousands of exercises spread across numerous language tracks. Each one is a fun and interesting challenge designed to teach you a little more about the features of a language.
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      amd64: x86_64
      386: i386
    apps:
      exercism:
        plugs: ["home", "network", "removable-media","personal-files"]
    plugs:
      personal-files:
        write:
        - $HOME/
