language: go

sudo: false

go:
  - "1.10.x"
  - "1.11.x"
  - tip

install:
  # install dep
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - ./.travis.gofmt.sh
  - go test -cover ./...
